CSS - Three - Column - Layout - Addy Abid
AddyAbid/c0821-code-solutions pull request #19
Opened 2021-08-21 02:51 UTC by AddyAbid

<img width="1084" alt="Screen Shot 2021-08-20 at 7 48 43 PM" src="https://user-images.githubusercontent.com/85080021/130308299-35e6481a-a7cf-48b2-b4f7-3030458dc8d8.png">

2021-08-23 17:09 UTC, codingcodymiller requested changes
Hey Addy! Your text alignment is incorrect as compared to the example, and your images still need to be centered as well. Please revise and submit a new screenshot once you have done so!

2021-08-23 20:19 UTC, AddyAbid commented
<img width="981" alt="Screen Shot 2021-08-23 at 1 18 04 PM" src="https://user-images.githubusercontent.com/85080021/130513749-27d90d18-3451-45a4-adbd-1eadf6140a09.png">

2021-08-24 00:24 UTC, codingcodymiller requested changes
Great work on this!! A couple notes for you:

2021-08-24 00:24 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  flex-wrap: wrap;
This can be removed, this class is not a flexbox since it doesn't have `display: flex`, so this line does nothing.

2021-08-24 00:24 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
You should make this class something like `text-center`, as of right now the name doesn't match its purpose.

2021-08-24 00:47 UTC, AddyAbid commented
<img width="976" alt="Screen Shot 2021-08-23 at 5 46 33 PM" src="https://user-images.githubusercontent.com/85080021/130537823-c8c015f8-9056-4123-96c4-042e217cf3e7.png">

2021-08-24 16:27 UTC, codingcodymiller approved these changes
Great work on this!! 🎉

2021-08-24 16:57 UTC, merged