CSS - Canvas - Medical - Addy Abid
AddyAbid/c0821-code-solutions pull request #25
Opened 2021-08-24 04:20 UTC by AddyAbid

https://user-images.githubusercontent.com/85080021/130555128-2a731ce1-133b-473f-828b-4eb9e6c9e943.mp4

2021-08-25 00:17 UTC, codingcodymiller requested changes
Hey Addy! Your alignment of the button and text in the "Ready to learn more?" row is a bit off as compared to the example, please revise and resubmit with a new screenshot to show the fix.

2021-08-25 02:36 UTC, AddyAbid commented
![_Users_addyabid_repos_c0821-code-solutions_css-canvas-medical_index html](https://user-images.githubusercontent.com/85080021/130717256-00ba7b1c-4fdb-447a-8dd5-9de1f26c2e52.png)

2021-08-29 23:20 UTC, AddyAbid commented
![_Users_addyabid_repos_c0821-code-solutions_css-canvas-medical_index html (1)](https://user-images.githubusercontent.com/85080021/131268520-9603b32f-7bd1-4ddf-b02c-efddffff5a01.png)

2021-08-31 18:23 UTC, codingcodymiller requested changes
Great updates on this! A few more notes for you:

2021-08-31 18:23 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      </div>
Shouldn't all of these be a child of a `div` with the `column-50` class? I doubt you want just your first link to take up 50% of the available width on its own.

2021-08-31 18:23 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
Why does this need to be absolute? `col-text` is already `absolute`. If you need more space between this element and its siblings, use `margin` or `padding`

2021-08-31 18:23 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
Same here, this likely doesn't need to be `absolute`

2021-09-05 04:37 UTC, AddyAbid commented
![_Users_addyabid_repos_c0821-code-solutions_css-canvas-medical_index html (2)](https://user-images.githubusercontent.com/85080021/132115438-10ab5679-f18e-40c3-b594-a4465d0e41fa.png)

2021-09-07 16:17 UTC, codingcodymiller approved these changes
Great work!!!

2021-09-07 16:52 UTC, merged