Javascript - Light - Bulb - Addy Abid
AddyAbid/c0821-code-solutions pull request #40
Opened 2021-08-31 22:06 UTC by AddyAbid

https://user-images.githubusercontent.com/85080021/131581929-a40abdf7-ccaa-42a7-9a92-ac82b6fb0239.mp4

2021-08-31 22:14 UTC, codingcodymiller requested changes
Great start! One note for you:

2021-08-31 22:14 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  }
This looks like it will work if you turn the light on and off once, but not after that. You should be able to turn the light on and off repetitively.

2021-09-01 02:46 UTC, AddyAbid commented
https://user-images.githubusercontent.com/85080021/131603450-1786d141-71f3-414e-ab61-5f817509b23c.mp4

2021-09-01 17:49 UTC, codingcodymiller approved these changes
Great work!!

2021-09-02 00:36 UTC, merged