CSS - Transitions - Addy Abid
AddyAbid/c0821-code-solutions pull request #42
Opened 2021-09-01 04:01 UTC by AddyAbid

https://user-images.githubusercontent.com/85080021/131609724-fa4fa1f1-63ea-4127-bb7c-c78c148aefac.mp4

2021-09-01 17:25 UTC, codingcodymiller requested changes

2021-09-01 17:25 UTC, codingcodymiller commented on css-transitions/styles.css
> +}
There are already rulesets for these elements, you should add your styling to those rather than making new rulesets

2021-09-02 03:20 UTC, AddyAbid commented
https://user-images.githubusercontent.com/85080021/131776390-eadf39ee-093e-4d01-875b-5ca7ab1ced9a.mp4

2021-09-02 16:40 UTC, codingcodymiller approved these changes

2021-09-02 16:41 UTC, merged