String - Manipulation - 1 - Addy Abid
AddyAbid/c0821-code-solutions pull request #45
Opened 2021-09-02 02:10 UTC by AddyAbid

![_Users_addyabid_repos_c0821-code-solutions_string-manipulation-1_index html](https://user-images.githubusercontent.com/85080021/131770097-38c2f9c2-a349-4c26-a470-7dafd7898565.png)

2021-09-02 17:54 UTC, codingcodymiller requested changes
Great start! A couple notes for you:

2021-09-02 17:54 UTC, codingcodymiller commented on string-manipulation-1/src/get-words.js
> +      }
I'm not sure I fully understand the point of this loop. What is this doing? How does it relate to your pseudocode?

2021-09-02 17:54 UTC, codingcodymiller commented on string-manipulation-1/src/is-vowel.js
> +  } else if (char === 'a' || char === 'e' || char === 'i' || char === 'o' || char === 'u') {
You should just put all these conditions in one `if`, there's no need to separate it into separate blocks, since the work is the same for both.

2021-09-14 04:35 UTC, AddyAbid commented
![_Users_addyabid_repos_c0821-code-solutions_string-manipulation-1_index html (1)](https://user-images.githubusercontent.com/85080021/133195637-19c20993-99c9-4e30-a7c4-1f617dafcc67.png)

2021-09-14 17:10 UTC, codingcodymiller approved these changes

2021-09-14 17:32 UTC, merged