Object - Manipulation - 1
AddyAbid/c0821-code-solutions pull request #54
Opened 2021-09-07 16:51 UTC by AddyAbid

![_Users_addyabid_repos_c0821-code-solutions_object-manipulation-1_index html](https://user-images.githubusercontent.com/85080021/132382291-5d345a48-adb9-450f-a219-4c4266e6d680.png)

2021-09-07 22:06 UTC, codingcodymiller requested changes

2021-09-07 22:06 UTC, codingcodymiller commented on object-manipulation-1/src/get-keys.js
> +  } return output;
Please always make sure `return` statements are on their own line.

2021-09-14 04:26 UTC, AddyAbid commented
![Screen Shot 2021-09-13 at 9 25 43 PM](https://user-images.githubusercontent.com/85080021/133194919-2bea7b37-f499-4ccd-b3fc-5e538aaf97bc.png)

2021-09-14 17:30 UTC, codingcodymiller approved these changes

2021-09-14 17:32 UTC, merged