HTML - Forms- Addy Abid
AddyAbid/c0821-code-solutions pull request #7
Opened 2021-08-17 20:09 UTC by AddyAbid

![Screen Shot 2021-08-17 at 1 08 01 PM](https://user-images.githubusercontent.com/85080021/129793492-a08005ae-c065-439e-97e6-894bf8d68ff4.png)

2021-08-17 20:20 UTC, codingcodymiller requested changes
Good start here!! A few notes for you:

2021-08-17 20:20 UTC, codingcodymiller commented on html-forms/index.html
> +        <label>
This `label` isn't configured correctly to match with the form control element it is paired with. The `label` and the form control element it is associated with both need a specific attribute with a matching value. The attributes are mentioned in the instructions and the documentation, please re-read them and try to find the way to properly configure a `label` element.

2021-08-17 20:20 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="coding is cool">Why is coding cool?</label>
There should not be spaces in the value here, you should use `kebab-case`. Spaces in attribute values generally means multiple values are being assigned to that attribute.

2021-08-17 20:20 UTC, codingcodymiller commented on html-forms/index.html
> +        <label for="coding is cool">Why is coding cool?</label>
Also, it is not configured correctly, just like the previous `label`

2021-08-17 20:20 UTC, codingcodymiller commented on html-forms/index.html
> +      <input type="radio" name="language" value="Javascript" /> Javascript
The text for each of these inputs should be a `label` element that is properly configured to match with the `input`

2021-08-17 20:20 UTC, codingcodymiller commented on html-forms/index.html
> +      <input type="checkbox" name="sign up" value="Sign me up!"/> Sign me up!
"Sign me up!" should be a `label` element that is properly configured to match with the `input`

2021-08-17 20:20 UTC, codingcodymiller commented on html-forms/index.html
> +      </div>
This should be a `label`

2021-08-18 02:26 UTC, AddyAbid commented
<img width="838" alt="Screen Shot 2021-08-17 at 7 24 45 PM" src="https://user-images.githubusercontent.com/85080021/129826768-8e93559e-b2f5-4ab3-953c-c8cbcad6c3e1.png">

2021-08-18 16:05 UTC, codingcodymiller approved these changes

2021-08-18 16:55 UTC, merged